# MLAKSDeploy Pipeline

trigger:
  batch: true
  branches:
    include:
    - master
    
variables:
- group: AzureKeyVault

jobs:
- job: MLAKSDeployAMLJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      which conda
      conda env create -f environment.yml
      conda env list
      conda activate MLAKSDeployAML
      conda env list
      echo Login Azure Account
      az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
      cd {{cookiecutter.project_name}}
      echo Execute 00_AMLConfiguration.ipynb
      papermill 00_AML_Configuration.ipynb 00_AML_Configuration_Output.ipynb \
        --log-output \
        --no-progress-bar \
        -k python3 \
        -p subscription_id $(azuresubscription) \
        -p resource_group $(azureresourcegroup) \
        -p workspace_name $(workspacename) \
        -p workspace_region $(azureregion) \
        -p tenant_id $(sptenent) \
        -p username $(spidentity) \
        -p password $(spsecret)
    displayName: '00_AML_Configuration.ipynb'

  - template: steps/papermill.yml
    parameters:
      notebook: 01_DataPrep.ipynb
      location: {{cookiecutter.project_name}}

  - bash: |
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate MLAKSDeployAML
      echo Execute Resource Group Delete
      existResponse=$(az group exists -n $(azureresourcegroup))
      if [ "$existResponse" == "true" ]; then
        echo Deleting project resource group
        az group delete --name $(azureresourcegroup) --yes
      else
        echo Project resource group did not exist
      fi
      echo Done Cleanup
    displayName: 'Backup Cleanup'
    condition: or(canceled(),failed())


