name: az-ml-realtime-score
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - pylint
  - pandas
  - pip:
    - papermill
    - azureml-core
    - pylint-junit
    - junit-xml
    - Microsoft-AI-Azure-Utilities==0.2.0
